// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsdczvnmcjdocxyioymm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZGN6dm5tY2pkb2N4eWlveW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTIzMDYsImV4cCI6MjA2MTc2ODMwNn0.yOmnkyuGngv2fvd2eSsn_r1KkBt_lWwTZvmw0_V5Jdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);